name: Validate Commit

on:
  push:
    branches:
    - main
    - 'fix/*'
    - 'feature/*'
    - 'support/*'
    paths:
    - '**'
    - '!docs/**'
    - '!new-cli/**'

  pull_request:
    branches:
    - main
    - 'support/*'
    paths:
    - '**'
    - '!docs/**'
    - '!new-cli/**'

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    name: DotNet Format
    steps:
      - uses: actions/checkout@v3
      -
        name: Setup .NET SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: '7.0.x'
      -
        name: Run Format Build solution
        run: dotnet format ./build/ --verify-no-changes
      -
        name: Run Format GitVersion solution
        run: dotnet format ./src/ --exclude **/AddFormats/ --verify-no-changes
